title: Computer Science History
description: A brief and gentle introduction to computer science.
template:
  repo: computer-science-history-template
  name: computer-science-history
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
