title: Computer Science History
description: A brief and gentle introduction to computer science.
template:
  repo: computer-science-history-template
  name: computer-science-history
  description: Learning resources and assignments.
before:
  - type: createIssue
    title: 'Video: Early Computing'
    body: early-computing.md
steps:
  - title: 'Video: Early Computing'
    description: 'Early Computing: Crash Course Computer Science'
    event: issues.closed
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
        issue: 'Video: Early Computing'
    video: 'https://www.youtube.com/embed/O5nskjZ_GoI'
